### ISSUE TITLE
404 on initial setup

### ISSUE THREAD

**Issue by npandu** [bezoerb/generator-sf#74]
? Would you like to use the Symfony "Standard Edition" distribution 4.1.4 (latest) Yes
? Would you like to enable Git for this project (includes post-merge hook)? No
     info Fetching https://github.com/symfony/symfony-standard/archive/v4.1.4.zip ...
     info This might take a few moments
events.js:183
      throw er; // Unhandled 'error' event
      ^

HTTPError: Response code 404 (Not Found)
    at EventEmitter.ee.on.res (C:\Users\Home\AppData\Roaming\npm\node_modules\generator-sf\node_modules\got\index.js:250:24)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at Immediate.setImmediate [as _onImmediate] (C:\Users\Home\AppData\Roaming\npm\node_modules\generator-sf\node_modules\got\index.js:99:8)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by bezoerb** [comment]
This generator is currently not maintained due to lack of time. The values are generated from actual symfony live data but the last time I checked symfony 3 was the new hot thing ;)

So symfony 3 should work fine.
If you want to do a PR to make it compatible with SF4 i would be very happy 😃

**Comment by npandu** [comment]
Thanks, It works great with Symfony 3.

I will try to make a PR sometimes later 👍
